.TH assist 1 "2018-12-12" "1.0.1
.
.SH NAME
assist \- ASIM Semi Automatic Schedule Tool
.
.SH SYNOPSIS
.SY assist
.OP \-rocon-time time
.OP \-rocoff-time time
.OP \-rocoff-wait time
.OP \-rocon-file file
.OP \-rocoff-file file
.OP \-roc-margin time
.OP \-saa time
.OP \-azm time
.OP \-ceron-time time
.OP \-ceroff-time time
.OP \-cer-time time
.OP \-cer-before time
.OP \-cer-after time
.OP \-cer-before-roc time
.OP \-cer-after-roc time
.OP \-cer-crossing time
.OP \-ceron-file file
.OP \-ceroff-file file
.OP \-alliop file
.OP \-instrlist file
.OP \-resolution time
.OP \-keep-comment
.OP \-base-time datetime
.OP \-list
.OP \-list-periods
.OP \-ignore
.RI < trajectory.csv >
.IR
.YS
.SY assist
.OP \-rocon-time time
.OP \-rocoff-time time
.OP \-rocoff-wait time
.OP \-rocon-file file
.OP \-rocoff-file file
.OP \-roc-margin time
.OP \-saa time
.OP \-azm time
.OP \-ceron-time time
.OP \-ceroff-time time
.OP \-cer-time time
.OP \-cer-before time
.OP \-cer-after time
.OP \-cer-before-roc time
.OP \-cer-after-roc time
.OP \-cer-crossing time
.OP \-ceron-file file
.OP \-ceroff-file file
.OP \-alliop file
.OP \-instrlist file
.OP \-resolution time
.OP \-keep-comment
.OP \-base-time datetime
.OP \-list
.OP \-list-periods
.OP \-ignore
.OP \-config
.RI < config.toml >
.IR
.YS
.SY assist
.OP \-ingest
.OP \-config
.RI < config.toml >
.IR
.RI < list.csv >
.IR
.YS
.SY assist
.OP \-ingest
.RI < list.csv >
.IR
.YS
.SY assist
.OP \-help
.YS
.YS
.SY assist
.OP \-version
.YS
.
.SH DESCRIPTION
assist implements the algorithm to create schedules that put the MXGS and MMIA
instruments of ASIM in a correct configuration for ISS eclipses and SAA crossing.
.
.SS ROCON SCHEDULING
.nr step 1 1
The following steps describe how assist schedule a ROCON:
.IP \n[step]
schedule ROCON at time of entering eclipse + rocon-wait
.IP \n+[step]
no SAA crossing, ROCON done
.IP \n+[step]
duration SAA crossing lesser than threshold, double the duration of AZM. If ROCON
overlaps with [start SAA, start SAA+2*AZM], schedule ROCON at end of interval
.IP \n+[step]
ROCON starts during AZM (SAA enter or exit), move ROCON time at end of AZM
.IP \n+[step]
ROCON ends during AZM (SAA enter or exit), move ROCON time start at end of AZM
.
.SS ROCOFF SCHEDULING
.nr step 1 1
The following steps describe how assist schedule a ROCOFF:
.IP \n[step]
schedule ROCOFF at time of exiting eclipse - rocoff-time
.IP \n+[step]
no SAA crossing, ROCOFF done
.IP \n+[step]
duration SAA crossing lesser than threshold, double the duration of AZM. If ROCOFF
overlaps with [start SAA, start SAA+2*AZM], schedule ROCOFF at start of interval
.IP \n+[step]
ROCOFF ends during AZM (SAA enter or exit), move ROCON time start at start
of SAA - rocoff-time
.IP \n+[step]
ROCOFF starts during AZM (SAA enter or exit), move ROCOFF time at start
of SAA - rocoff-time
.
.SS CER SCHEDULING
.P
assist has two different ways to schedule Cosmic Event Rejections.
.P
The first, CERON and CEROFF are scheduled outside of eclipses. In this case, one
CERON is scheduled for multiple eclipses while there are SAA crossing of at least
[cer-crossing]. As soon as there is an eclipse without a SAA crossing, a CEROFF
is scheduled.
.P
The second, CERON and CEROFF are scheduled around every SAA crossing during an
eclipse.
.
.SS CER, ROC CONFLICTS
To be written
.
.SH OPTIONS
.SS INPUT/OUTPUT OPTIONS
.TP
.BI \-base-time\  DATETIME
Start the schedule with the first eclipse starting after the given DATETIME
(RFC3339 format)
.TP
.BI \-alliop\  FILE
Save schedule to FILE
.TP
.BI \-instrlist\  FILE
Save instrument list to FILE
.TP
.B \-config
Use a configuration file to set various parameters. When this flag is set, the
configuration file should always be the first argument given to assist
.TP
.B \-ingest
Read a possibly modified list to re create a schedule
.TP
.BI \-resolution\  TIME
Interval of TIME between two rows in the trajectory file
.
.SS ROC OPTIONS
.TP
.BI \-rocon-time\  TIME
ROCON expected execution time
.TP
.BI \-rocoff-time\  TIME
ROCOFF expected execution time
.TP
.BI \-rocon-wait\  TIME
wait TIME after entering eclipse before scheduling ROCON
.TP
.BI \-roc-margin\  TIME
Minimum margin TIME between end of ROCON and start of ROCOFF
.TP
.BI \-rocon-file\  FILE
Use FILE with commands for ROCON
.TP
.BI \-rocoff-file\  FILE
Use FILE with commands for ROCOFF
.TP
.BI \-azm\  TIME
Expected on-board AZM dururation
.TP
.BI \-saa\  TIME
SAA duration to resolve conflict between ROCON and ROCOFF
.
.SS CER OPTIONS
.TP
.BI \-cer-time\  TIME
TIME before entering eclipse to switch CERON/CEROFF
.TP
.BI \-cer-crossing\  TIME
Minimum crossing TIME of SAA and eclipse to switch CERON
.TP
.BI \-cer-before\  TIME
Schedule CERON TIME before SAA enter during eclipse
.TP
.BI \-cer-after\  TIME
Schedule CEROFF TIME before SAA exit during eclipse
.TP
.BI \-cer-before-roc\  TIME
Delay CERON before when conflict with ROCON/ROCOFF
.TP
.BI \-cer-after-roc\  TIME
Delay CEROFF before when conflict with ROCON/ROCOFF
.TP
.BI \-ceron-file\  FILE
Use FILE with commands for CERON
.TP
.BI \-ceroff-file\  FILE
Use FILE with commands for CEROFF
.
.SS MISC OPTIONS
.TP
.B \-list
Print the list of blocks that will be schedule from the trajectory
.TP
.B \-list-periods
Print the list of eclipses and SAA from the trajectory
.TP
.B \-ignore
When using list, ignore constraints set to ROCON/ROCOFF
.TP
.B \-keep-comment
Write comments from the commands file into the schedule file. Setting this flag
to true force also assist to add its own comments.
.TP
.B \-version
Print version and exit
.TP
.B \-help
Print a help message and exit
.
.SH EXAMPLES
.EX
set values via a config file instead of command line options:
.RS
.B assist -config /etc/asim/ops.toml
.RE
.EE
.LP
.EX
gives the list of commands that could be scheduled from the given trajectory:
.RS
.B assist -list /tmp/trajectory.csv
.RE
.EE
.LP
.EX
print the list of commands that could be scheduled directly from the output of
inspect:
.RS
.B inspect -d 24h -i 10s -f csv https://celestrak.com/NORAD/elements/stations.txt | assist -list
.RE
.EE
.
.SH SEE ALSO
inspect(1), assist.toml(5), assist.list(5), inspect.toml(5), trajectory.csv(5)
.
.SH FILES
.I /usr/share/doc/asim-ccn26/examples/assist.toml
.RS
example for an assist configuration file
.RE
