.TH assist 1 "2018-12-12" "1.0.1
.
.SH NAME
assist \- ASIM Semi Automatic Schedule Tool
.
.SH SYNOPSIS
assist [-base-time] [-list] <trajectory>
assist [-base-time] [-list] [-config] <config.toml>
.
assist [-base-time] [-rocon-time] [-rocoff-time] [-cer-time] [-cer-crossing] [-azm] [-saa] <trajectory>
.
assist [-base-time] [-ingest] <list>
assist [-base-time] [-ingest] [-config] <config.toml> <list>
.
.SH DESCRIPTION
assist implements the algorithm to create schedules that put the MXGS and MMIA
instruments of ASIM in a correct configuration for ISS eclipses and SAA crossing.
.
.SH OPTIONS
.SS INPUT/OUTPUT OPTIONS
.TP
.BI \-base-time\  DATETIME
Start the schedule with the first eclipse starting after the given DATETIME
(RFC3339 format)
.TP
.BI \-alliop\  FILE
Save schedule to FILE
.TP
.BI \-instrlist\  FILE
Save instrument list to FILE
.TP
.B \-config
Use a configuration file to set various parameters. When this flag is set, the
configuration file should always be the first argument given to assist
.TP
.B \-ingest
Read a possibly modified list to re create a schedule
.TP
.BI \-resolution\  TIME
Interval of TIME between two rows in the trajectory file
.
.SS ROC OPTIONS
.TP
.BI \-rocon-time\  TIME
ROCON expected execution time
.TP
.BI \-rocoff-time\  TIME
ROCOFF expected execution time
.TP
.BI \-rocon-wait\  TIME
wait TIME after entering eclipse before scheduling ROCON
.TP
.BI \-roc-margin\  TIME
Minimum margin TIME between end of ROCON and start of ROCOFF
.TP
.BI \-rocon-file\  FILE
Use FILE with commands for ROCON
.TP
.BI \-rocoff-file\  FILE
Use FILE with commands for ROCOFF
.TP
.BI \-azm\  TIME
Expected on-board AZM dururation
.TP
.BI \-saa\  TIME
SAA duration to resolve conflict between ROCON and ROCOFF
.
.SS CER OPTIONS
.TP
.BI \-cer-time\  TIME
TIME before entering eclipse to switch CERON/CEROFF
.TP
.BI \-cer-crossing\  TIME
Minimum crossing TIME of SAA and eclipse to switch CERON
.TP
.BI \-cer-before\  TIME
Schedule CERON TIME before SAA enter during eclipse
.TP
.BI \-cer-after\  TIME
Schedule CEROFF TIME before SAA exit during eclipse
.TP
.BI \-cer-before-roc\  TIME
Delay CERON before when conflict with ROCON/ROCOFF
.TP
.BI \-cer-after-roc\  TIME
Delay CEROFF before when conflict with ROCON/ROCOFF
.TP
.BI \-ceron-file\  FILE
Use FILE with commands for CERON
.TP
.BI \-ceroff-file\  FILE
Use FILE with commands for CEROFF
.
.SS MISC OPTIONS
.TP
.B \-list
Print the list of blocks that will be schedule from the trajectory
.TP
.B \-list-periods
Print the list of eclipses and SAA from the trajectory
.TP
.B \-ignore
When using list, ignore constraints set to ROCON/ROCOFF
.TP
.B \-keep-comment
Write comments from the commands file into the schedule file. Setting this flag
to true force also assist to add its own comments.
.TP
.B \-version
Print version and exit
.TP
.B \-help
Print a help message and exit
.
.SH EXAMPLES
.EX
set values via a config file instead of command line options:
.RS
.B assist -config /etc/asim/ops.toml
.RE
.EE
.LP
.EX
gives the list of commands that could be scheduled from the given trajectory:
.RS
.B assist -list /tmp/trajectory.csv
.RE
.EE
.LP
.EX
print the list of commands that could be scheduled directly from the output of
inspect:
.RS
.B inspect -d 24h -i 10s -f csv https://celestrak.com/NORAD/elements/stations.txt | assist -list
.RE
.EE
.
.SH SEE ALSO
inspect(1), assist.toml(5), assist.list(5), inspect.toml(5), trajectory.csv(5)
.
.SH FILES
.I /usr/share/doc/asim-ccn26/examples/assist.toml
.RS
example for an assist configuration file
.RE
