.TH assist 5 "2018-12-12" "1.0.0"
.
.SH NAME
assist.toml \- assist configuration file
.
.SH DESCRIPTION
assist implements the algorithm to create schedules that put the MXGS and MMIA
instruments of ASIM in a correct configuration for ISS eclipses and SAA crossing.
.
.SH GENERAL TABLE
.TP
.BI alliop " string"
Save schedule to FILE
.TP
.BI instrlist " string"
Save instrument list to FILE
.TP
.BI keep-comment " boolean"
Write comments from the commands file into the schedule file. Setting this flag
to true force also assist to add its own comments.
.TP
.BI path " string"
read trajectory from FILE
.TP
.BI resolution " duration"
Interval of TIME between two rows in the trajectory file
.
.SH DELTA TABLE
.TP
.BI wait " duration"
wait TIME after entering eclipse before scheduling ROCON
.TP
.BI rocon " duration"
ROCON expected execution time
.TP
.BI rocoff " duration"
ROCOFF expected execution time
.TP
.BI cer " duration"
TIME before entering eclipse to switch CERON/CEROFF
.TP
.BI crossing " duration"
Minimum crossing TIME of SAA and eclipse to switch CERON
.TP
.BI azm " duration"
Expected on-board AZM dururation
.TP
.BI saa " duration"
SAA duration to resolve conflict between ROCON and ROCOFF
.TP
.BI margin " duration"
Minimum margin TIME between end of ROCON and start of ROCOFF
.TP
.BI cer-before " duration"
Schedule CERON TIME before SAA enter during eclipse
.TP
.BI cer-after " duration"
Schedule CEROFF TIME before SAA exit during eclipse
.TP
.BI cer-before-roc " duration"
Delay CERON before when conflict with ROCON/ROCOFF
.TP
.BI cer-after-roc " duration"
Delay CEROFF before when conflict with ROCON/ROCOFF
.
.SH COMMANDS TABLE
.TP
.BI rocon " string"
Use FILE with commands for ROCON
.TP
.BI rocoff " string"
Use FILE with commands for ROCOFF
.TP
.BI ceron " string"
Use FILE with commands for CERON
.TP
.BI ceroff " string"
Use FILE with commands for CEROFF
.
.SH EXAMPLES
.EX
alliop = "/var/run/asim/alliop.txt"
instrlist = "/var/run/asim/instrlist.txt"
keep-comment = true

path = "/var/run/asim/trajectory.csv"
resolution = "10s"

[delta]
wait     = "90s"
rocon    = "50s"
rocoff   = "80s"
cer      = "0s"
crossing = "120s"
azm      = "40s"
saa      = "30s"
margin   = "0"

cer-before     = "50s"
cer-after      = "15s"
cer-before-roc = "45s"
cer-after-roc  = "10s"

[commands]
rocon  = "/etc/asim/MXGS_ROCON.txt"
rocoff = "/etc/asim/MXGS_ROCOFF.txt"
ceron  = "/etc/asim/MMIA_CERON.txt"
ceroff = "/etc/asim/MMIA_CEROFF.txt"
.EE
.
.SH SEE ALSO
inspect(1), assist(1), assist.list(5), inspect.toml(5), trajectory.csv(5)
